version: "3"

services:
  db:
    image: postgis/postgis
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - postgis_data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - ${PORT}:8000
    depends_on:
      - db
    volumes:
      - .:/code/
      - ./static:/static
      - ./media:/media

volumes:
  postgis_data:
