# Generated by Django 4.1.7 on 2023-03-24 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Links',
            new_name='Link',
        ),
    ]
