# Generated by Django 4.1.7 on 2023-04-25 09:59

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinings', '0003_rename_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dining',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dining',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=django.contrib.gis.geos.point.Point(36.2971, 59.5953), null=True, srid=4326),
        ),
    ]
